[package]
name = "noctum-micro"
version = "0.1.0"
publish = false
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = ["fast-math", "wide-4", "downsampling", "filter-gain-limited"]
audio-profiling = ["diagnostics", "synth-core/profiling"]
diagnostics = []
fast-math = ["synth-core/fast-math"]
wide-4 = ["synth-core/wide-4"]
wide-1 = ["synth-core/wide-1"]
downsampling = ["synth-core/downsampling"]
filter-distributed-newton = ["synth-core/filter-distributed-newton"]
filter-scalar-feedback = ["synth-core/filter-scalar-feedback"]
filter-gain-limited = ["synth-core/filter-gain-limited"]
filter-huovilainen = ["synth-core/filter-huovilainen"]
filter-cascaded-svf = ["synth-core/filter-cascaded-svf"]
oscillator-polyblep = ["synth-core/oscillator-polyblep"]
usb-audio-test-tone = []
usb-audio-raw-test = []
bench-factory-banks = ["dep:tools-micro"]

[dependencies]
embassy-sync.workspace = true
heapless = "0.9"
synth-core.workspace = true
wmidi.workspace = true
tools-micro = { path = "tools-micro", optional = true }

[dev-dependencies]
critical-section = { version = "1.2", features = ["std"] }

[target.'cfg(target_arch = "arm")'.dependencies]
cortex-m.workspace = true
cortex-m-rt.workspace = true
defmt.workspace = true
defmt-rtt.workspace = true
embassy-daisy.workspace = true
embassy-executor.workspace = true
embassy-futures.workspace = true
embassy-stm32.workspace = true
embassy-time.workspace = true
panic-probe.workspace = true
static_cell.workspace = true

[[bin]]
name = "noctum-micro"
path = "src/main.rs"
test = false
bench = false

[[bin]]
name = "bench-dsp"
path = "src/bin/bench-dsp.rs"
required-features = ["audio-profiling"]
test = false
bench = false

[[bin]]
name = "bench-factory-banks"
path = "src/bin/bench-factory-banks.rs"
required-features = ["audio-profiling", "bench-factory-banks"]
test = false
bench = false
