use std::{env, fs, path::PathBuf};

const HARMONIC_LIMITS: [u16; 33] = [
    1023, 860, 723, 607, 510, 428, 359, 301, 253, 212, 178, 149, 125, 105, 88, 73, 61, 51, 42, 35,
    29, 24, 20, 16, 13, 10, 8, 6, 5, 4, 3, 2, 1,
];

fn main() {
    let output = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by Cargo"))
        .join("wavetable_mip_lookup.rs");
    let mut source = String::from(
        "// Generated by synth-core/build.rs; do not edit.\n\
         const MIP_SELECTION_LOOKUP: [MipSelection; 1024] = [\n",
    );
    for safe_harmonics in 0..1024_u16 {
        let richer = HARMONIC_LIMITS
            .iter()
            .position(|limit| *limit <= safe_harmonics)
            .unwrap_or(HARMONIC_LIMITS.len() - 1);
        let leaner = (richer + 1).min(HARMONIC_LIMITS.len() - 1);
        let richer_amount = if safe_harmonics == 0 || richer == 0 || richer == leaner {
            1.0
        } else {
            let lower = f64::from(HARMONIC_LIMITS[richer]);
            let upper = f64::from(HARMONIC_LIMITS[richer - 1]);
            (f64::from(safe_harmonics) / lower).ln() / (upper / lower).ln()
        }
        .clamp(0.0, 1.0);
        source.push_str(&format!(
            "    MipSelection {{ richer: {richer}, leaner: {leaner}, richer_amount: {richer_amount:.9e}_f32 }},\n"
        ));
    }
    source.push_str("];\n");
    fs::write(output, source).expect("write generated wavetable mip lookup");
    println!("cargo::rerun-if-changed=build.rs");
}
