//! Prophet '08 factory preset names from Prophet_08_Programs_v1.0.syx.

pub const FACTORY_PRESET_NAMES: [[&str; 128]; 2] = [
    [
        "Wagnerian",
        "Tom Sawyer",
        "T8 Strings",
        "Epic Brass",
        "Dual Bass",
        "Bridge Seq",
        "Soft Triangles",
        "Double Arp",
        "Fusion Bass",
        "Listen",
        "MOONSTER",
        "Tarkus  (F1 seq)",
        "BiSync",
        "Lo Drone",
        "Crystal",
        "Aliens",
        "Slither Lead",
        "Konserve",
        "Evolver",
        "Deep",
        "Modern Music",
        "SlowWah FastClav",
        "P'08 in da House",
        "Chaos",
        "Verse",
        "Tonga Conga",
        "Delay<MW>EarlRef",
        "Talker",
        "Hi Brass Bells",
        "Ice Planet",
        "DIY Phazorand",
        "Braggomat",
        "4OscStrings",
        "Sunset Mono Gtr",
        "Tape Vox",
        "PlayLO n LETitGO",
        "P5 3-2 sync",
        "Santiago",
        "Classic Square",
        "Anakeys",
        "Velocihornet",
        "bOOmChik",
        "Chamber Strings",
        "Fortunate Guy",
        "Bandpassed",
        "Sus4 Stack",
        "Poly Bass",
        "Analog Bliss",
        "Sync Floyd Dark",
        "PolyOddy 08",
        "Hot Alias Chick",
        "Suitcase Layer",
        "Blip",
        "SeeSaw SeeSquare",
        "Spit 'n Spank",
        "Toto French Horn",
        "Colliochord",
        "Vector Wheels 4V",
        "Helicopters",
        "EvoPad",
        "Basement",
        "Service",
        "Small Pipes  A&B",
        "Sample Hold X 4",
        "Hard Pad",
        "Rubycorn Dream",
        "Suitcase",
        "VariClap",
        "Opening Up",
        "Al Arma !",
        "Tape Saturation",
        "N.U.N.I.",
        "Ski Canyon Delay",
        "Broken Wing",
        "Rasp Bass",
        "SizzleSaw Lead",
        "Prophet Piano",
        "Royal Horns",
        "Sunrise",
        "Stop It",
        "CheeseIntro",
        "Pressure Squared",
        "Snoopy Bass",
        "Harp Arp",
        "Musette",
        "SheWantsToDance",
        "Tinny Thinny",
        "Half Live",
        "The Darkness",
        "No Corn Yet",
        "Finale",
        "Mr. Fusion",
        "Clean Glass Bell",
        "Dark Fizzz Keys",
        "2 Much Red Bull",
        "Fiiilters",
        "HiwayPatrolBass",
        "Geisha",
        "SyncGlider   a/b",
        "Clean Jim",
        "Rezzy Neeyowng",
        "Tricky Sweeper",
        "Synchronizer A/B",
        "Breaking Glass",
        "Deep eMotion",
        "Tutti",
        "Waver",
        "Squeezee",
        "Bass Pedals",
        "CP35",
        "Seashore B:Wind",
        "PW Downsweep",
        "TriPulseAttkLd",
        "Come Together",
        "Drop Da Bomb",
        "Frnknstein(Hold)",
        "Hellabass",
        "Mildessa",
        "Mosquito",
        "Eureka Pulse Mod",
        "Saw Upsweep",
        "Swirl",
        "Take Off",
        "Stretch",
        "Condor",
        "Box o' Morons",
        "Hood Beat",
        "Basic Program",
    ],
    [
        "AnalogWurlyRoids",
        "SynClav",
        "Brasscomp",
        "Epic Brass",
        "Octave Diver MW",
        "P3 and Rezlie",
        "Descending",
        "Phatt Sub",
        "Rare Peace",
        "Red Fizzz",
        "Lost In Thought",
        "More Cowbell",
        "PurityControl",
        "TonewheelOrgan",
        "MassiveFakePWM",
        "Seagulls",
        "Modular 5th",
        "Menace",
        "Mad Symphony",
        "Trancesexual",
        "Ambush",
        "MellowBass",
        "Rubber Rez",
        "WelcomeBack ELP",
        "Steel Cans",
        "ManInTheMoon",
        "BD",
        "Zen Master",
        "Pinball",
        "Heavy Weather",
        "80iesSynthPop",
        "Steps",
        "Dust Storm",
        "Geeky Mono",
        "Pig Pen",
        "Fired Bassist",
        "Direful",
        "Upright",
        "Solo Reed",
        "Universe",
        "Homeless",
        "Flutish",
        "Hoover Rave",
        "Key Waves",
        "Banana Split",
        "Peitsche",
        "Tube Fire",
        "Dirt Devil Rave",
        "noOB Brass 2pole",
        "Blow Up",
        "Git da funk out",
        "Virtuously",
        "Pipe Leslie",
        "Double Pick Bass",
        "Alu Tines",
        "LowKey",
        "Zardoz",
        "P`08 Pulse",
        "Carillon",
        "Compressed",
        "Arp Pad",
        "Steady",
        "Different",
        "Thunder & Rain",
        "Whassup ?",
        "Layered Lead",
        "E3Rep",
        "Spartacus",
        "Dial Tonez",
        "French Horn Pad",
        "Pickaxe Bass",
        "Synth String Pad",
        "Blubber 2",
        "Chime",
        "Cirrus",
        "Lead Stack",
        "Hammond Glass",
        "Bugger",
        "Pure Prophet",
        "Oh Bee",
        "Missa",
        "Filter Chant",
        "Sync Floyd",
        "SilentMovie",
        "Nebula Pad",
        "Gemini Lead",
        "Theremin Rookie",
        "Forbidden Planet",
        "Soft Dark Bite",
        "ChirpStrings",
        "FakeDelay",
        "The Big Diss",
        "Subtractive",
        "Alien Race",
        "Combo Organ",
        "Percy",
        "MightyDecent",
        "Catweazle",
        "73 Rubbers   A&B",
        "GX Stack",
        "P's a Model",
        "Ignite My Flame",
        "Analog Vector",
        "Real Bad Osc",
        "Detuned Poles",
        "Scrape Dry Rust",
        "Pulse Shifter",
        "Nuthin'ButFilter",
        "Mud Acid",
        "R2D2 & C3PO",
        "Rubato",
        "Skinny Phatty",
        "Four Sided Tri",
        "Church  MW=stops",
        "Stacker",
        "The X-Strings",
        "Tuned Trash Lids",
        "iMover      B=fx",
        "73 Rubber Bites",
        "Podpogo pop",
        "Homeorgan",
        "RubberpunchBass",
        "ReversePlayback",
        "Come In",
        "Yump",
        "Softie",
        "A/D Test",
        "Filter Test",
    ],
];

pub fn factory_preset_name(bank: u8, program: u8) -> Option<&'static str> {
    if bank > 1 { return None; }
    FACTORY_PRESET_NAMES.get(usize::from(bank))?.get(usize::from(program)).copied()
}

pub fn program_filename(bank: u8, program: u8) -> Option<String> {
    if bank > 1 || program > 127 { return None; }
    let bank_number = bank + 5;
    let name = sanitize_filename(factory_preset_name(bank, program)?);
    Some(format!("F{bank_number}-{:03}-{name}", program + 1))
}

fn sanitize_filename(name: &str) -> String {
    let mut output = String::with_capacity(name.len());
    let mut separator = false;
    for character in name.chars() {
        if character.is_ascii_alphanumeric() || matches!(character, '-' | '_') {
            output.push(character);
            separator = false;
        } else if !separator && !output.is_empty() {
            output.push('_');
            separator = true;
        }
    }
    while output.ends_with('_') { output.pop(); }
    output
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn filenames_use_f5_and_f6_prefixes() {
        assert_eq!(program_filename(0, 0).as_deref(), Some("F5-001-Wagnerian"));
        assert_eq!(program_filename(1, 0).as_deref(), Some("F6-001-AnalogWurlyRoids"));
        assert_eq!(program_filename(2, 0), None);
    }
}
