//! Prophet Rev2 factory preset names as published by Sequential.

pub const FACTORY_PRESET_NAMES: [[&str; 128]; 4] = [
    [
        "LosVangelis2041",
        "All That Glitter",
        "Le Matignon",
        "Balalaika2017",
        "Discovery Pad",
        "BoiteMusique",
        "Play Nice.",
        "BigUnisonSync",
        "Jungleizer",
        "Vibranova",
        "Tweezurrr",
        "Sons Pad",
        "CloudyBass",
        "Mod Me",
        "Rutger Lead",
        "Ultra Split",
        "Pizz I Cato",
        "FM Bass",
        "Horn Busker",
        "Robert Rock",
        "Escape 2 New York",
        "Prrg Nexus",
        "Windy Space Pad",
        "Intellect Lead",
        "Plush Pluck",
        "PolyTine",
        "Chariots",
        "Tangerillo Arp",
        "DeepSyncBass",
        "Marshmallow Pie",
        "Whist Pad",
        "Eventide",
        "Dirty Watergates",
        "Pixels",
        "ClassicBrass 24dB",
        "TribalTomArpWhl",
        "Organized",
        "Sitcom Piano",
        "Ice Bowl",
        "Skip Feet",
        "Jupiter Poor",
        "Dreamlines",
        "Big Chords",
        "VeloPluckster",
        "REVerent",
        "Sync Bass",
        "Kalimba Dance",
        "Futura Pad",
        "Kick 2 U",
        "Director’s Cut",
        "AT Agro Bass",
        "Bright Keys",
        "Bass Reso Classic",
        "HoJo’s Plucks",
        "Dull Vox Stereo",
        "Harpseechord",
        "Strangers",
        "Lush House",
        "Prophet Pad",
        "WaveFlavors",
        "GroovyGate",
        "Finger Bass",
        "Choir",
        "XfadePluck",
        "Kick 1 Time",
        "Delay lay lay lay",
        "Can’t Kill Me",
        "GatedCommunity",
        "Flyte Solo",
        "Cloud Save",
        "Dark Angels",
        "MassmorphWheel",
        "E Harp",
        "Rez Bass",
        "ActionOnWheels",
        "Twilight Ritual",
        "Morgoth’s Boot",
        "Wobbly Stab",
        "Stalactites",
        "Quirky Air",
        "NaturalLeader",
        "Utility Pad A",
        "PW@yerFingertips",
        "Left Hand Pad",
        "Moon Sword",
        "RandoSync",
        "MeeDevil",
        "Trem Pad",
        "Arpbass",
        "Melancholic Wobble",
        "GatedPolyPluk",
        "Sita",
        "Metal Danse",
        "DoipSalad",
        "Racer",
        "FierceFlangePad",
        "Amato’s Elektro",
        "Freestyle Bee",
        "She Sheila",
        "Quiver",
        "Squishy Bass",
        "Piano",
        "Surgical",
        "Sizzling",
        "Brutality Bass",
        "RippynFlangeLead",
        "Termina",
        "Solid Pad",
        "Vox Numana",
        "Curtis Drum",
        "Hanna-Barbashop",
        "Industrial Noise",
        "Nova Pad",
        "Muted Pluck",
        "MysteriousSpaces",
        "8-Bit",
        "Swarmatron",
        "Melt-Fi",
        "Flange Strings",
        "Taking the Hi-Pass",
        "Ars Synthetica",
        "Shift Strings",
        "StabbySaw",
        "Wave",
        "Auf nach Oberheim",
        "Delicious Saw",
        "Thx4TheMemory",
        "Engine Room",
    ],
    [
        "VeloStrings",
        "StereoBrass",
        "Psyncopath",
        "Blomp In the Night",
        "StruckHarpeggio",
        "MIDIstack",
        "Boombox Bap",
        "Drizzle",
        "Housings",
        "Bronto Bass",
        "Stretch",
        "PunchBox",
        "TighterBrassee",
        "Bonzai Arp",
        "Dominator",
        "Agitater Fader",
        "Chord Shadowland",
        "YammyTribute",
        "P5 Bass",
        "RillyTrilly",
        "Gentle Phase",
        "DoubleWideBass",
        "Big N Bouncy",
        "Simple Brass",
        "Moving",
        "Drank",
        "Chastain Halls",
        "1 Finger Rave",
        "Stack Split Lo",
        "Pink Synthi",
        "VeloPulses",
        "Over Lead",
        "C.S.A.T.",
        "ARP Splitter",
        "The Beat",
        "Squareklavier",
        "Phoenix Rising",
        "Atonal Bells",
        "Rev2 Horns",
        "Arpogenic",
        "BalineseOrgan",
        "Bip Bass",
        "Ensembull",
        "Plastipoke",
        "UnderMySkin",
        "Delicate Arp",
        "Circular Fifths",
        "HorribleLead",
        "Bubble Pad",
        "Clear The Room",
        "Anaconga",
        "Industries Bass",
        "Warm & Fuzzy",
        "Pitter Pattern",
        "Trancetta",
        "New Wave Finger",
        "PerkyVeloOrgan",
        "Analog Wave Seque",
        "Funky",
        "Livid Saws",
        "Gamelan Ensemble",
        "Lost In Octavia",
        "Hollo Program",
        "Duck Sauce",
        "Mod Sync Lead",
        "LoTech Jam",
        "Sync Pulsar",
        "Pulse Train",
        "Approaching",
        "Broadways",
        "For Bernie W",
        "Double Impact",
        "ShiftingSands",
        "Canada Sync",
        "Skinny Synth",
        "Bass",
        "Calypso Rise",
        "Let’s Go Slow",
        "Chamberlinginio",
        "Nu Smooth",
        "Cats In Space...",
        "Canadian",
        "Quaver Bass",
        "S.Genviv",
        "Wirey Thing",
        "Cheap Wurly",
        "Bent With Press",
        "Hammer Bell",
        "Warehouse Bass",
        "Flute",
        "Mod Pad",
        "Shibuya Station",
        "Sync II REV2",
        "Padded Cell",
        "Eternal",
        "SynBass-P5Lead",
        "Leads United",
        "Sidechain Bass",
        "4ainA",
        "Doc Arp",
        "Da Classic Mode",
        "Ekoplexer Bass",
        "Talk Nerdy 2 Me",
        "The Score",
        "Dark Organ",
        "CR Box",
        "DigLeads",
        "Toy Mallet",
        "Vocal Lead",
        "Funk Saw Brother",
        "Hallow Bass Arp",
        "Syncastic",
        "Make Noise Perc",
        "It’s Back",
        "Warptik",
        "Swelling Pad",
        "Percutron X",
        "Wobble Choir",
        "Wet Synth Brass",
        "Soundtreck",
        "Anabelle",
        "Elektrobass",
        "Sweep REVerse",
        "Rezo Concertina",
        "Tinny80’s",
        "Rip It Down",
        "Sync Drone",
        "Mosquito",
    ],
    [
        "Ceremony",
        "JustHoldOctaves",
        "Big Synth Brass",
        "Clicky & Mellow",
        "SyncWavetables",
        "Funky Bends",
        "4M Hiero",
        "Simple Bell",
        "SmalltownSplit",
        "Organic",
        "Pluck LFO",
        "String Machine",
        "FrenchSkaters",
        "Reeds & Tines",
        "Knock Knock",
        "Red n Blue Swede",
        "Noisy Pluck",
        "KaliPluckArp",
        "Bwem Bass",
        "Glow of the Alps",
        "Triton’s Epoch",
        "Angry Wheel",
        "Bock Box!",
        "Ultra Leader",
        "Squelchy Bass",
        "Sound Of Evolution",
        "EZ Drive Bass",
        "InstantHorrors",
        "Blood Vain",
        "Hard Tech",
        "TinnysizerLead",
        "JMJ Style",
        "Leeder",
        "Goldsmith Split",
        "Fugue Maker",
        "Piercer",
        "Funkz Bass",
        "JUMP!",
        "How To Fake Delay",
        "Runnerz Arp",
        "Sparkeys",
        "Moove Along Sir",
        "Poly Bliss",
        "Blip N Time",
        "Soft Metals",
        "Bass Panther",
        "Body Flow",
        "FakeCS80",
        "ChiptuneMemories",
        "Flooty",
        "Stack Overflow",
        "Arp Pluck",
        "Glockenspiel",
        "Gravity Chips",
        "Whopping Bass",
        "Under Water",
        "Bloom + Scrape",
        "Speed Demon",
        "Ja! Was denn nun ?",
        "Sum Rad Fade In",
        "MaxxFatt",
        "Tap Central",
        "Jello PAD",
        "Pop Chords",
        "Level Up!",
        "StruckPlumbing",
        "Zstring",
        "Chord Stab Maj7",
        "Sparklepress",
        "Brooding 80s Pop",
        "Strange Pad",
        "Granulations",
        "Repulsor Lift",
        "Maximo Lead",
        "Frantasia Pad",
        "Magma Edge Bass",
        "Small Bell",
        "Tight Comp",
        "Tin Udu Arp",
        "Brass Pulse Pad",
        "ClavBassSawLead",
        "Ruff Bass",
        "Flood`s 700",
        "Grit 4String",
        "Sly Guy Lead Whl",
        "Glassbell",
        "Luscious Pad",
        "Irish Jig Solo Split",
        "The Leaders",
        "Waver Layers",
        "Combo Bass",
        "Grinder Choir",
        "Bass-Sqr Lead",
        "Cycle Bass",
        "Dreams",
        "TRIbal Bass",
        "Hollow & String MW",
        "Dub Tech Bass Arp",
        "Crummy Strings",
        "Space Sine",
        "Colossul Clav",
        "Stringer Order",
        "Moving Points",
        "Escaping",
        "Simple Poly",
        "Acid Wheel",
        "RaspyBassics",
        "Moving Strings",
        "Sadbass",
        "Carpenter Bees",
        "Chord Haven",
        "AftrprtyOrkestra",
        "Trance Party",
        "WafeBeater",
        "Sync Pad",
        "Wheel House",
        "Big Bad Pad",
        "Delay Hit",
        "Omni",
        "Feedback Machine",
        "Dystopian Pad",
        "Talkbox",
        "BetterThanVintage",
        "Cat Pad",
        "Madness",
        "8-Bit Cathedral",
        "Slow Bold Pad",
        "support@dsi.com",
    ],
    [
        "ResAttackPad",
        "Ethereal Pluck",
        "Pulse Drops",
        "BuffBigbass",
        "DangerTril",
        "Tribute Solo 1",
        "Breakin’",
        "Interstellar Pad",
        "ClavioMello",
        "Stop! Summertime",
        "Wave Perks",
        "Pincher Piano",
        "SynthPop 101 A",
        "Deep House Organ",
        "80s Highway Bass",
        "String Ensemble",
        "Dark Star",
        "Dual Melody",
        "Solid Keys",
        "Digital Dance",
        "New Musik",
        "80’s Lite",
        "Fryguy",
        "Tribass-P5Res",
        "Old Elec Piano",
        "Pastoral Arp",
        "Sine Kerve",
        "Resonance Comp",
        "Electric Pulse",
        "F’wipian Comp",
        "The Soft Side",
        "Banana Split",
        "Octave Chunk",
        "Overly OB Brass",
        "Arp Chord",
        "Triangleforte",
        "Randomizor",
        "LA Bass",
        "Clicky Keys",
        "Big & Dirty",
        "End is Near",
        "Rev2 Clav",
        "Phaser Bass",
        "Ambient",
        "Beatz",
        "D-50`esque",
        "Close Bass",
        "ModWheel Sync",
        "Arpsichord",
        "Space Mystery",
        "Octave Bass",
        "Sexican Seq",
        "Solid Bass",
        "RetroKoto",
        "Bandero",
        "A Strange Pulse",
        "Singing Along",
        "Rowdy Brass Club",
        "Phazed",
        "PuffnStuff",
        "Morning Woodwind",
        "Euro Trumpet",
        "PluckyGateArp",
        "Blue Chord",
        "Seaside Pad",
        "Mutant Bass",
        "Rising to Hit",
        "Poly Rhythmik",
        "Bel Idee",
        "Vocal",
        "Rubberband Arp",
        "Twilight Run",
        "Solo Daze",
        "Beef Wublet Rev2",
        "Clean Club Minor",
        "BigBronzePercs",
        "TinToys",
        "3B or not 2B",
        "Bass 2 Taste",
        "DCO Chorus",
        "Modem Attack Pad",
        "ChorusCopter",
        "Fast Times At DSI",
        "EZ Synth Pad",
        "SlappySplit",
        "BigWheel",
        "Polythrob",
        "Dramatic",
        "Pad Chill",
        "BoilerBass",
        "SolinaStrings",
        "Abyss",
        "Human Numan",
        "Cylliptical",
        "Wave Walkabout",
        "BigBass",
        "Evolving RezPad",
        "Pen & Paper",
        "String Machine Oct",
        "Vibe Verb",
        "Pound4Pound",
        "Kraut Funk",
        "Jupiter Sky",
        "Lower Floors Arp",
        "Wormhole",
        "Gleam On",
        "Warehouse Stab",
        "Glide Keys",
        "Walking Arp",
        "Practicing Weird",
        "Bass-Voices Split",
        "Pluckyrimbapan",
        "Brass Stax",
        "Weather Bass",
        "Game Over",
        "ChamberStringy",
        "Fat Batch",
        "Live Orchestra",
        "L0ada Bazass",
        "Space Invaders",
        "Cold Breath",
        "Slow Burn",
        "Gently Sweeps",
        "Pulse Pickin",
        "Mod Madness",
        "Filter Test",
        "Symple Sawz",
        "A/D Test",
    ],
];

pub fn factory_preset_name(bank: u8, program: u8) -> Option<&'static str> {
    if bank > 7 {
        return None;
    }
    FACTORY_PRESET_NAMES
        .get(usize::from(bank % 4))?
        .get(usize::from(program))
        .copied()
}

pub fn program_filename(bank: u8, program: u8) -> Option<String> {
    if bank > 7 || program > 127 {
        return None;
    }
    let bank_kind = if bank < 4 { 'U' } else { 'F' };
    let bank_number = bank % 4 + 1;
    let name = sanitize_filename(factory_preset_name(bank, program)?);
    Some(format!(
        "{bank_kind}{bank_number}-{:03}-{name}",
        program + 1
    ))
}

fn sanitize_filename(name: &str) -> String {
    let mut output = String::with_capacity(name.len());
    let mut separator = false;
    for character in name.chars() {
        if character.is_ascii_alphanumeric() || matches!(character, '-' | '_') {
            output.push(character);
            separator = false;
        } else if !separator && !output.is_empty() {
            output.push('_');
            separator = true;
        }
    }
    while output.ends_with('_') {
        output.pop();
    }
    output
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn factory_table_is_complete_and_has_page_sentinels() {
        assert!(
            FACTORY_PRESET_NAMES
                .iter()
                .flatten()
                .all(|name| !name.is_empty())
        );
        assert_eq!(FACTORY_PRESET_NAMES[0][0], "LosVangelis2041");
        assert_eq!(FACTORY_PRESET_NAMES[1][127], "Mosquito");
        assert_eq!(FACTORY_PRESET_NAMES[2][127], "support@dsi.com");
        assert_eq!(FACTORY_PRESET_NAMES[3][127], "A/D Test");
    }

    #[test]
    fn filenames_map_all_banks_and_sanitize_names() {
        assert_eq!(
            program_filename(0, 0).as_deref(),
            Some("U1-001-LosVangelis2041")
        );
        assert_eq!(program_filename(5, 127).as_deref(), Some("F2-128-Mosquito"));
        assert_eq!(
            program_filename(6, 127).as_deref(),
            Some("F3-128-support_dsi_com")
        );
        for (bank, prefix) in [
            (0, "U1"),
            (1, "U2"),
            (2, "U3"),
            (3, "U4"),
            (4, "F1"),
            (5, "F2"),
            (6, "F3"),
            (7, "F4"),
        ] {
            assert!(program_filename(bank, 0).unwrap().starts_with(prefix));
            assert!(program_filename(bank, 127).unwrap().contains("-128-"));
        }
        assert_eq!(program_filename(8, 0), None);
    }
}
