//! Prophet Rev2-compatible sequencer patch data and typed edits.
//!
//! Runtime clocking and playback deliberately live outside these structures. This
//! module is the fixed-capacity, lossless representation shared by patch storage,
//! MIDI codecs, the desktop editor, and the audio engine.

use crate::{patch::ModDestination, program::LayerId};

pub const GATED_TRACK_COUNT: usize = 4;
pub const GATED_STEP_COUNT: usize = 16;
pub const POLY_LANE_COUNT: usize = 6;
pub const POLY_STEP_COUNT: usize = 64;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "snake_case"))]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum GatedDestination {
    #[default]
    Off,
    Modulation(ModDestination),
    /// Rev2 destination 53. Meaningful on tracks 2 and 4, where it slews the
    /// value generated by the preceding odd-numbered track.
    Slew,
}

impl GatedDestination {
    pub fn from_rev2_raw(raw: u16) -> Self {
        match raw {
            0 => Self::Off,
            53 => Self::Slew,
            value => Self::Modulation(ModDestination::from_index(usize::from(value.min(52)))),
        }
    }

    pub fn rev2_raw(self) -> u16 {
        match self {
            Self::Off => 0,
            Self::Modulation(destination) => destination.index() as u16,
            Self::Slew => 53,
        }
    }

    pub const fn modulation(self) -> Option<ModDestination> {
        match self {
            Self::Modulation(destination) => Some(destination),
            Self::Off | Self::Slew => None,
        }
    }
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "snake_case"))]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum SequencerType {
    Gated,
    #[default]
    Polyphonic,
}

impl SequencerType {
    pub const fn from_index(index: usize) -> Self {
        if index == 0 {
            Self::Gated
        } else {
            Self::Polyphonic
        }
    }

    pub const fn index(self) -> usize {
        match self {
            Self::Gated => 0,
            Self::Polyphonic => 1,
        }
    }
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "snake_case"))]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum GatedSequencerMode {
    #[default]
    Normal,
    NoReset,
    NoGate,
    NoGateNoReset,
    KeyStep,
}

impl GatedSequencerMode {
    pub const fn from_index(index: usize) -> Self {
        match index {
            1 => Self::NoReset,
            2 => Self::NoGate,
            3 => Self::NoGateNoReset,
            4 => Self::KeyStep,
            _ => Self::Normal,
        }
    }

    pub const fn index(self) -> usize {
        match self {
            Self::Normal => 0,
            Self::NoReset => 1,
            Self::NoGate => 2,
            Self::NoGateNoReset => 3,
            Self::KeyStep => 4,
        }
    }

    pub const fn gates_envelopes(self) -> bool {
        matches!(self, Self::Normal | Self::NoReset | Self::KeyStep)
    }

    pub const fn resets_on_key(self) -> bool {
        matches!(self, Self::Normal | Self::NoGate | Self::KeyStep)
    }
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "snake_case"))]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum GatedStep {
    #[default]
    Reset,
    Value(u8),
    Rest,
}

impl GatedStep {
    pub const fn from_rev2_raw(raw: u16) -> Self {
        match raw {
            0..=125 => Self::Value(raw as u8),
            126 => Self::Reset,
            _ => Self::Rest,
        }
    }

    pub const fn rev2_raw(self) -> u16 {
        match self {
            Self::Value(value) => (if value > 125 { 125 } else { value }) as u16,
            Self::Reset => 126,
            Self::Rest => 127,
        }
    }
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GatedTrack {
    pub destination: GatedDestination,
    pub steps: [GatedStep; GATED_STEP_COUNT],
}

impl Default for GatedTrack {
    fn default() -> Self {
        Self {
            destination: GatedDestination::Off,
            steps: [GatedStep::Reset; GATED_STEP_COUNT],
        }
    }
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GatedSequence {
    pub tracks: [GatedTrack; GATED_TRACK_COUNT],
}

impl Default for GatedSequence {
    fn default() -> Self {
        Self {
            tracks: [GatedTrack::default(); GATED_TRACK_COUNT],
        }
    }
}

impl GatedSequence {
    pub fn apply(&mut self, update: SequenceUpdate) {
        match update {
            SequenceUpdate::GatedDestination { track, destination } => {
                if let Some(track) = self.tracks.get_mut(usize::from(track)) {
                    track.destination = destination;
                }
            }
            SequenceUpdate::GatedStep { track, step, value } => {
                if let Some(step) = self
                    .tracks
                    .get_mut(usize::from(track))
                    .and_then(|track| track.steps.get_mut(usize::from(step)))
                {
                    *step = value;
                }
            }
            SequenceUpdate::Type(_)
            | SequenceUpdate::GatedMode(_)
            | SequenceUpdate::PolyNote { .. }
            | SequenceUpdate::PolyVelocity { .. }
            | SequenceUpdate::PolyLaneStep { .. } => {}
        }
    }
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "snake_case"))]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PolyNote {
    Note(u8),
    Tie,
}

impl PolyNote {
    pub const fn from_rev2_raw(raw: u16) -> Self {
        if raw <= 127 {
            Self::Note(raw as u8)
        } else {
            Self::Tie
        }
    }

    pub const fn rev2_raw(self) -> u16 {
        match self {
            Self::Note(note) => (if note > 127 { 127 } else { note }) as u16,
            Self::Tie => 128,
        }
    }
}

impl Default for PolyNote {
    fn default() -> Self {
        Self::Note(60)
    }
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "snake_case"))]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum PolyVelocity {
    #[default]
    Reset,
    Rest,
    Velocity(u8),
}

impl PolyVelocity {
    pub const fn from_rev2_raw(raw: u16) -> Self {
        match raw {
            128 => Self::Rest,
            129..=255 => Self::Velocity((raw - 128) as u8),
            _ => Self::Reset,
        }
    }

    pub const fn rev2_raw(self) -> u16 {
        match self {
            Self::Reset => 0,
            Self::Rest => 128,
            Self::Velocity(velocity) => {
                128 + if velocity == 0 {
                    1
                } else if velocity > 127 {
                    127
                } else {
                    velocity
                } as u16
            }
        }
    }
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct PolyLaneStep {
    pub note: PolyNote,
    pub velocity: PolyVelocity,
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PolyStep {
    pub lanes: [PolyLaneStep; POLY_LANE_COUNT],
}

impl Default for PolyStep {
    fn default() -> Self {
        Self {
            lanes: [PolyLaneStep::default(); POLY_LANE_COUNT],
        }
    }
}

impl PolyStep {
    pub fn is_reset(self) -> bool {
        self.lanes
            .iter()
            .all(|lane| lane.velocity == PolyVelocity::Reset)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PolySequence {
    pub steps: [PolyStep; POLY_STEP_COUNT],
}

impl PolySequence {
    pub fn apply(&mut self, update: SequenceUpdate) {
        match update {
            SequenceUpdate::PolyNote { step, lane, value } => {
                if let Some(lane) = self
                    .steps
                    .get_mut(usize::from(step))
                    .and_then(|step| step.lanes.get_mut(usize::from(lane)))
                {
                    lane.note = value;
                }
            }
            SequenceUpdate::PolyVelocity { step, lane, value } => {
                if let Some(lane) = self
                    .steps
                    .get_mut(usize::from(step))
                    .and_then(|step| step.lanes.get_mut(usize::from(lane)))
                {
                    lane.velocity = value;
                }
            }
            SequenceUpdate::PolyLaneStep { step, lane, value } => {
                if let Some(lane) = self
                    .steps
                    .get_mut(usize::from(step))
                    .and_then(|step| step.lanes.get_mut(usize::from(lane)))
                {
                    *lane = value;
                }
            }
            SequenceUpdate::Type(_)
            | SequenceUpdate::GatedMode(_)
            | SequenceUpdate::GatedDestination { .. }
            | SequenceUpdate::GatedStep { .. } => {}
        }
    }

    pub fn reset_mask(&self) -> u64 {
        let mut mask = 0u64;
        for (index, step) in self.steps.iter().enumerate() {
            if step.is_reset() {
                mask |= 1 << index;
            }
        }
        mask
    }
}

#[cfg(feature = "serde")]
impl serde::Serialize for PolySequence {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serde::Serialize::serialize(self.steps.as_slice(), serializer)
    }
}

#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for PolySequence {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        struct PolySequenceVisitor;

        impl<'de> serde::de::Visitor<'de> for PolySequenceVisitor {
            type Value = PolySequence;

            fn expecting(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                formatter.write_str("exactly 64 polyphonic sequencer steps")
            }

            fn visit_seq<A>(self, mut sequence: A) -> Result<Self::Value, A::Error>
            where
                A: serde::de::SeqAccess<'de>,
            {
                let mut steps = [PolyStep::default(); POLY_STEP_COUNT];
                for (index, step) in steps.iter_mut().enumerate() {
                    *step = sequence
                        .next_element()?
                        .ok_or_else(|| serde::de::Error::invalid_length(index, &self))?;
                }
                if sequence.next_element::<PolyStep>()?.is_some() {
                    return Err(serde::de::Error::invalid_length(POLY_STEP_COUNT + 1, &self));
                }
                Ok(PolySequence { steps })
            }
        }

        deserializer.deserialize_seq(PolySequenceVisitor)
    }
}

impl Default for PolySequence {
    fn default() -> Self {
        Self {
            steps: [PolyStep::default(); POLY_STEP_COUNT],
        }
    }
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct LayerSequence {
    pub sequencer_type: SequencerType,
    pub gated_mode: GatedSequencerMode,
    pub gated: GatedSequence,
    pub poly: PolySequence,
}

impl LayerSequence {
    /// Normalizes values that can be constructed directly or deserialized from
    /// non-Rev2 patch files.
    pub fn validate(&mut self) {
        for track in &mut self.gated.tracks {
            if track.destination == GatedDestination::Modulation(ModDestination::Off) {
                track.destination = GatedDestination::Off;
            }
            for step in &mut track.steps {
                if let GatedStep::Value(value) = step {
                    *value = (*value).min(125);
                }
            }
        }
        for step in &mut self.poly.steps {
            for lane in &mut step.lanes {
                if let PolyNote::Note(note) = &mut lane.note {
                    *note = (*note).min(127);
                }
                if let PolyVelocity::Velocity(velocity) = &mut lane.velocity {
                    *velocity = (*velocity).clamp(1, 127);
                }
            }
        }
    }

    /// Applies a validated edit. Invalid track/step/lane addresses are ignored.
    pub fn apply(&mut self, update: SequenceUpdate) {
        match update {
            SequenceUpdate::Type(value) => self.sequencer_type = value,
            SequenceUpdate::GatedMode(value) => self.gated_mode = value,
            SequenceUpdate::GatedDestination { .. } | SequenceUpdate::GatedStep { .. } => {
                self.gated.apply(update);
            }
            SequenceUpdate::PolyNote { .. }
            | SequenceUpdate::PolyVelocity { .. }
            | SequenceUpdate::PolyLaneStep { .. } => {
                self.poly.apply(update);
            }
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SequenceUpdate {
    Type(SequencerType),
    GatedMode(GatedSequencerMode),
    GatedDestination {
        track: u8,
        destination: GatedDestination,
    },
    GatedStep {
        track: u8,
        step: u8,
        value: GatedStep,
    },
    PolyNote {
        step: u8,
        lane: u8,
        value: PolyNote,
    },
    PolyVelocity {
        step: u8,
        lane: u8,
        value: PolyVelocity,
    },
    PolyLaneStep {
        step: u8,
        lane: u8,
        value: PolyLaneStep,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SequencerRecordCommand {
    Start,
    Stop,
    SetCursor(u8),
    MoveCursor(i8),
    InsertRest,
    InsertTie,
    InsertReset,
    ClearStep,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SequencerTransportCommand {
    Start,
    Continue,
    Stop,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SequenceClear {
    Gated,
    Polyphonic,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SequencerFeedback {
    RecordStatus {
        layer: LayerId,
        recording: bool,
        cursor: u8,
    },
    StepChanged {
        layer: LayerId,
        step: u8,
        value: PolyStep,
    },
    RecordOverflow {
        layer: LayerId,
        cursor: u8,
    },
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rev2_special_values_are_exact_and_normalized() {
        assert_eq!(GatedStep::from_rev2_raw(125), GatedStep::Value(125));
        assert_eq!(GatedStep::from_rev2_raw(126), GatedStep::Reset);
        assert_eq!(GatedStep::from_rev2_raw(127), GatedStep::Rest);
        assert_eq!(GatedStep::from_rev2_raw(u16::MAX), GatedStep::Rest);
        assert_eq!(PolyNote::from_rev2_raw(127), PolyNote::Note(127));
        assert_eq!(PolyNote::from_rev2_raw(128), PolyNote::Tie);
        assert_eq!(PolyNote::from_rev2_raw(u16::MAX), PolyNote::Tie);
        assert_eq!(PolyVelocity::from_rev2_raw(0), PolyVelocity::Reset);
        assert_eq!(PolyVelocity::from_rev2_raw(127), PolyVelocity::Reset);
        assert_eq!(PolyVelocity::from_rev2_raw(128), PolyVelocity::Rest);
        assert_eq!(PolyVelocity::from_rev2_raw(129), PolyVelocity::Velocity(1));
        assert_eq!(
            PolyVelocity::from_rev2_raw(255),
            PolyVelocity::Velocity(127)
        );
    }

    #[test]
    fn invalid_edit_addresses_do_not_mutate_sequence() {
        let mut sequence = LayerSequence::default();
        let expected = sequence;
        sequence.apply(SequenceUpdate::GatedStep {
            track: u8::MAX,
            step: u8::MAX,
            value: GatedStep::Rest,
        });
        sequence.apply(SequenceUpdate::PolyNote {
            step: u8::MAX,
            lane: u8::MAX,
            value: PolyNote::Tie,
        });
        sequence.apply(SequenceUpdate::PolyLaneStep {
            step: u8::MAX,
            lane: u8::MAX,
            value: PolyLaneStep {
                note: PolyNote::Tie,
                velocity: PolyVelocity::Velocity(127),
            },
        });
        assert_eq!(sequence, expected);
    }

    #[test]
    fn whole_poly_lane_update_applies_note_and_velocity_together() {
        let mut sequence = LayerSequence::default();
        let value = PolyLaneStep {
            note: PolyNote::Tie,
            velocity: PolyVelocity::Velocity(127),
        };
        sequence.apply(SequenceUpdate::PolyLaneStep {
            step: 12,
            lane: 4,
            value,
        });
        assert_eq!(sequence.poly.steps[12].lanes[4], value);
    }

    #[test]
    fn validation_clamps_directly_constructed_payload_values() {
        let mut sequence = LayerSequence::default();
        sequence.gated.tracks[0].destination = GatedDestination::Modulation(ModDestination::Off);
        sequence.gated.tracks[0].steps[0] = GatedStep::Value(u8::MAX);
        sequence.poly.steps[0].lanes[0] = PolyLaneStep {
            note: PolyNote::Note(u8::MAX),
            velocity: PolyVelocity::Velocity(0),
        };
        sequence.validate();
        assert_eq!(sequence.gated.tracks[0].destination, GatedDestination::Off);
        assert_eq!(sequence.gated.tracks[0].steps[0], GatedStep::Value(125));
        assert_eq!(sequence.poly.steps[0].lanes[0].note, PolyNote::Note(127));
        assert_eq!(
            sequence.poly.steps[0].lanes[0].velocity,
            PolyVelocity::Velocity(1)
        );
    }

    #[cfg(feature = "serde")]
    #[test]
    fn serde_requires_exactly_sixty_four_poly_steps() {
        let sequence = PolySequence::default();
        let json = serde_json::to_string(&sequence).unwrap();
        assert_eq!(
            serde_json::from_str::<PolySequence>(&json).unwrap(),
            sequence
        );
        let mut short = serde_json::to_value(sequence).unwrap();
        short.as_array_mut().unwrap().pop();
        assert!(serde_json::from_value::<PolySequence>(short).is_err());
    }
}
