[package]
name = "embassy-daisy"
version = "0.1.0"
description = "Embassy board support package for Electro-Smith Daisy hardware"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository = "https://github.com/chris-zen/analog-synth"
keywords = ["embedded", "embassy", "daisy", "audio", "no-std"]
categories = ["embedded", "no-std"]

[package.metadata.docs.rs]
features = ["seed_1_1"]
targets = ["thumbv7em-none-eabihf"]

[features]
default = []
seed = []
seed_1_1 = []
seed_1_2 = []
patch_sm = []
sampling_rate_96khz = []
block_length_64 = []

[target.'cfg(target_arch = "arm")'.dependencies]
cortex-m.workspace = true
embassy-stm32.workspace = true
embassy-time.workspace = true
static_cell.workspace = true
stm32-fmc.workspace = true
