[package]
name = "embassy-daisy"
version = "0.1.0"
description = "Embassy board support package for Electro-Smith Daisy hardware"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository = "https://github.com/chris-zen/analog-synth"
keywords = ["embedded", "embassy", "daisy", "audio", "no-std"]
categories = ["embedded", "no-std"]
build = "build.rs"

[package.metadata.docs.rs]
features = ["seed_1_1"]
targets = ["thumbv7em-none-eabihf"]

[lib]
harness = false

[features]
default = []
seed = []
seed_1_1 = []
seed_1_2 = []
patch_sm = []
sampling_rate_96khz = []
block_length_64 = []

[dependencies]
cortex-m.workspace = true
embassy-stm32 = { version = "0.6.0", features = ["defmt", "stm32h750ib", "time-driver-any", "memory-x"] }
embassy-time.workspace = true
static_cell.workspace = true
stm32-fmc.workspace = true

[dev-dependencies]
embedded-test = { version = "0.7", default-features = false, features = ["semihosting"] }
cortex-m-rt.workspace = true
defmt.workspace = true
defmt-rtt.workspace = true
panic-probe.workspace = true
