#!/usr/bin/env python3
"""Generate the versioned external measured wavetable bank for Plan 07."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

import numpy as np


REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from scripts.evaluate_target_conditioned_ablations import best_phase_alignment  # noqa: E402
from scripts.fit_target_conditioned_oscillator import (  # noqa: E402
    DEFAULT_DERIVED,
    PHASE_BINS,
    profile_checksum,
    rust_float,
)
from scripts.fit_target_conditioned_oscillator_v2 import production_source  # noqa: E402


DEFAULT_MANIFEST = REPO_ROOT / (
    "plans/analog-osc/research/banks/korg-monologue-measured-bank-v1.json"
)
DEFAULT_BINARY = REPO_ROOT / (
    "target/analog-osc/banks/korg-monologue-measured-bank-v1.f32le"
)
DEFAULT_RUST = REPO_ROOT / "synth-core/src/dsp/measured_wavetable_profile.rs"
PROFILE_ID = "korg-monologue-measured-bank-v1"
TARGET_ID = "korg-monologue-v1"
WAVEFORMS = ("saw", "triangle", "square")
PITCH_COUNT = 36
TABLE_LENGTH = 2_048
BANK_REFERENCE_SAMPLE_RATE_HZ = 48_000.0
NYQUIST_GUARD = 0.45
BANK_SAMPLES = len(WAVEFORMS) * PITCH_COUNT * TABLE_LENGTH


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def fnv1a32(values: np.ndarray) -> int:
    result = 0x811C9DC5
    for byte in np.asarray(values, dtype="<f4").tobytes():
        result = ((result ^ byte) * 0x01000193) & 0xFFFFFFFF
    return result


def pitch_safe_table(cycle: np.ndarray, guard_frequency_hz: float) -> tuple[np.ndarray, int]:
    spectrum = np.fft.rfft(cycle)
    harmonic_limit = min(
        spectrum.size - 1,
        TABLE_LENGTH // 2 - 1,
        int(NYQUIST_GUARD * BANK_REFERENCE_SAMPLE_RATE_HZ / guard_frequency_hz),
    )
    spectrum[harmonic_limit + 1 :] = 0.0
    return np.fft.irfft(spectrum, n=TABLE_LENGTH).astype("<f4"), harmonic_limit


def waveform_tables(
    waveform: str, cycles: np.ndarray, frequencies: np.ndarray
) -> tuple[np.ndarray, list[float], list[int], list[float]]:
    train_indices = np.arange(0, cycles.shape[0], 2)
    output = np.empty(PITCH_COUNT * TABLE_LENGTH, dtype="<f4")
    phase_shifts = []
    harmonic_limits = []
    guard_frequencies = []
    for ordinal, index in enumerate(train_indices):
        cycle = cycles[index]
        if waveform == "saw":
            shift, _, cycle = best_phase_alignment(
                cycle, production_source(waveform, float(frequencies[index])), 0.0
            )
        else:
            shift = 0.0
        phase_shifts.append(float(shift))
        guard_index = min(index + 2, cycles.shape[0] - 1)
        guard_frequency = float(frequencies[guard_index])
        table, harmonic_limit = pitch_safe_table(cycle, guard_frequency)
        base = ordinal * TABLE_LENGTH
        output[base : base + TABLE_LENGTH] = table
        harmonic_limits.append(harmonic_limit)
        guard_frequencies.append(guard_frequency)
    return output, phase_shifts, harmonic_limits, guard_frequencies


def write_rust_metadata(path: Path, manifest: dict[str, Any], checksum: str) -> None:
    lines = [
        "//! Generated by scripts/generate_measured_wavetable_bank.py; do not edit.",
        "",
        f'pub const MEASURED_BANK_PROFILE_ID: &str = "{PROFILE_ID}";',
        f'pub const MEASURED_BANK_TARGET_ID: &str = "{TARGET_ID}";',
        "pub const MEASURED_BANK_MANIFEST_SHA256: &str =",
        f'    "{checksum}";',
        f"pub const MEASURED_BANK_FNV1A32: u32 = 0x{manifest['bank_binary']['fnv1a32']:08x};",
        f"pub const MEASURED_BANK_SAMPLE_COUNT: usize = {BANK_SAMPLES};",
        f"pub const MEASURED_BANK_TABLE_LENGTH: usize = {TABLE_LENGTH};",
        f"pub const MEASURED_BANK_REFERENCE_SAMPLE_RATE_HZ: f32 = {rust_float(BANK_REFERENCE_SAMPLE_RATE_HZ)};",
        "",
    ]
    for waveform, constant, maximum_constant in (
        ("saw", "MEASURED_SAW_FREQUENCIES_HZ", "MEASURED_SAW_MAXIMUM_HZ"),
        (
            "triangle",
            "MEASURED_TRIANGLE_FREQUENCIES_HZ",
            "MEASURED_TRIANGLE_MAXIMUM_HZ",
        ),
        ("square", "MEASURED_PULSE_FREQUENCIES_HZ", "MEASURED_PULSE_MAXIMUM_HZ"),
    ):
        values = manifest["waveforms"][waveform]["training_frequencies_hz"]
        lines.append(f"pub const {constant}: [f32; {PITCH_COUNT}] = [")
        lines.extend(f"    {rust_float(float(value))}," for value in values)
        lines.append("];\n")
        maximum = manifest["waveforms"][waveform]["maximum_supported_frequency_hz"]
        lines.append(f"pub const {maximum_constant}: f32 = {rust_float(float(maximum))};\n")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def build(derived_root: Path) -> tuple[np.ndarray, dict[str, Any]]:
    banks = []
    waveform_metadata = {}
    for waveform in WAVEFORMS:
        npz_path = derived_root / f"{waveform}-cycles-v1.npz"
        with np.load(npz_path) as source:
            cycles = np.asarray(source["median_cycles"], dtype=np.float64)
            frequencies = np.asarray(source["measured_frequency_hz"], dtype=np.float64)
        tables, phase_shifts, harmonic_limits, guard_frequencies = waveform_tables(
            waveform, cycles, frequencies
        )
        banks.append(tables)
        waveform_metadata[waveform] = {
            "source_npz_sha256": sha256_file(npz_path),
            "training_pitch_indices": list(range(0, cycles.shape[0], 2)),
            "training_frequencies_hz": frequencies[::2].tolist(),
            "phase_policy": (
                "global rotation aligned to production source"
                if waveform == "saw"
                else "importer upward-crossing landmark"
            ),
            "training_global_phase_shifts_cycles": phase_shifts,
            "pitch_safe_harmonic_limits": harmonic_limits,
            "pitch_guard_frequencies_hz": guard_frequencies,
            "maximum_supported_frequency_hz": float(frequencies[-1]),
        }
    bank = np.concatenate(banks).astype("<f4", copy=False)
    if bank.shape != (BANK_SAMPLES,) or not np.all(np.isfinite(bank)):
        raise ValueError(f"invalid generated bank {bank.shape}")
    manifest = {
        "schema_version": 1,
        "profile_id": PROFILE_ID,
        "target_id": TARGET_ID,
        "sample_format": "little-endian IEEE-754 float32",
        "layout": {
            "order": "waveform, training pitch, sample",
            "waveforms": list(WAVEFORMS),
            "pitch_count_per_waveform": PITCH_COUNT,
            "table_length": TABLE_LENGTH,
            "reference_sample_rate_hz": BANK_REFERENCE_SAMPLE_RATE_HZ,
            "nyquist_guard": NYQUIST_GUARD,
            "pitch_safety_policy": (
                "each training table is truncated for the next training pitch; "
                "the final table is truncated for the highest measured pitch"
            ),
            "sample_count": BANK_SAMPLES,
        },
        "phase_bins_source": PHASE_BINS,
        "waveforms": waveform_metadata,
        "bank_binary": {
            "repository_relative_path": str(DEFAULT_BINARY.relative_to(REPO_ROOT)),
            "bytes": int(bank.nbytes),
            "sample_count": int(bank.size),
            "fnv1a32": fnv1a32(bank),
        },
    }
    return bank, manifest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--derived-root", type=Path, default=DEFAULT_DERIVED)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--binary", type=Path, default=DEFAULT_BINARY)
    parser.add_argument("--rust-output", type=Path, default=DEFAULT_RUST)
    args = parser.parse_args()

    bank, manifest = build(args.derived_root)
    args.binary.parent.mkdir(parents=True, exist_ok=True)
    bank.tofile(args.binary)
    manifest["bank_binary"]["sha256"] = sha256_file(args.binary)
    checksum = profile_checksum(manifest)
    manifest["manifest_content_sha256"] = checksum
    args.manifest.parent.mkdir(parents=True, exist_ok=True)
    args.manifest.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    write_rust_metadata(args.rust_output, manifest, checksum)
    print(f"wrote {args.manifest}")
    print(f"wrote {args.binary}")
    print(f"wrote {args.rust_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
